### ISSUE TITLE
Markdown parser panics

### ISSUE THREAD

**Issue by tadeokondrak** [diamondburned/ningen#1]
"```\n\n"
```
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/yuin/goldmark/text.(*Segments).At(...)
	/home/tdeo/go/pkg/mod/github.com/yuin/goldmark@v1.1.30/text/segment.go:182
github.com/diamondburned/ningen/md.fenced._close(0x9746c0, 0xc000221040, 0x972820, 0xc00007fec0, 0x972d60, 0xc0002b9ce0)
	/home/tdeo/ningen/md/codeblock.go:162 +0x4e7
github.com/diamondburned/ningen/md.fenced.Parse(0x9747e0, 0xc0002e7200, 0x972820, 0xc00007fec0, 0x972d60, 0xc0002b9ce0, 0x0, 0x972820)
	/home/tdeo/ningen/md/codeblock.go:35 +0x197
github.com/yuin/goldmark/parser.(*parser).parseBlock(0xc000305500, 0x972a60, 0xc00007fec0, 0x9747e0, 0xc0002e7200, 0x972d60, 0xc0002b9ce0)
	/home/tdeo/go/pkg/mod/github.com/yuin/goldmark@v1.1.30/parser/parser.go:1163 +0x820
github.com/yuin/goldmark/parser.(*parser).Parse.func2(0x9747e0, 0xc0002e7200)
	/home/tdeo/go/pkg/mod/github.com/yuin/goldmark@v1.1.30/parser/parser.go:852 +0x7d
github.com/yuin/goldmark/parser.(*parser).walkBlock(0xc000305500, 0x9747e0, 0xc0002e7200, 0xc00029fd70)
	/home/tdeo/go/pkg/mod/github.com/yuin/goldmark@v1.1.30/parser/parser.go:1103 +0xf8
github.com/yuin/goldmark/parser.(*parser).walkBlock(0xc000305500, 0x9745a0, 0xc0002e7180, 0xc00029fd70)
	/home/tdeo/go/pkg/mod/github.com/yuin/goldmark@v1.1.30/parser/parser.go:1101 +0x9d
github.com/yuin/goldmark/parser.(*parser).Parse(0xc000305500, 0x9728e0, 0xc0002b9c70, 0x0, 0x0, 0x0, 0xc00029fe87, 0x9)
	/home/tdeo/go/pkg/mod/github.com/yuin/goldmark@v1.1.30/parser/parser.go:851 +0x2c4
github.com/diamondburned/ningen/md.Parse(0x7f312c3fc000, 0x5, 0x5, 0x0, 0x0, 0x0, 0x1305dc78, 0x7a0fe790092b)
	/home/tdeo/ningen/md/md.go:50 +0x29b
github.com/diamondburned/ningen/md.Fuzz(0x7f312c3fc000, 0x5, 0x5, 0x3)
	/home/tdeo/ningen/md/fuzz.go:6 +0x68
go-fuzz-dep.Main(0xc00029ff70, 0x1, 0x1)
	go-fuzz-dep/main.go:36 +0x1ad
main.main()
	github.com/diamondburned/ningen/md/go.fuzz.main/main.go:15 +0x52
exit status 2
```
">\n```\r"
```
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/yuin/goldmark/text.(*Segments).At(...)
	/home/tdeo/go/pkg/mod/github.com/yuin/goldmark@v1.1.30/text/segment.go:182
github.com/diamondburned/ningen/md.fenced._close(0x9746c0, 0xc0002263c0, 0x972820, 0xc00007ea20, 0x972d60, 0xc000265490)
	/home/tdeo/ningen/md/codeblock.go:162 +0x4e7
github.com/diamondburned/ningen/md.fenced.Parse(0x9747e0, 0xc0001fa700, 0x972820, 0xc00007ea20, 0x972d60, 0xc000265490, 0x0, 0x972820)
	/home/tdeo/ningen/md/codeblock.go:35 +0x197
github.com/yuin/goldmark/parser.(*parser).parseBlock(0xc00010e000, 0x972a60, 0xc00007ea20, 0x9747e0, 0xc0001fa700, 0x972d60, 0xc000265490)
	/home/tdeo/go/pkg/mod/github.com/yuin/goldmark@v1.1.30/parser/parser.go:1163 +0x820
github.com/yuin/goldmark/parser.(*parser).Parse.func2(0x9747e0, 0xc0001fa700)
	/home/tdeo/go/pkg/mod/github.com/yuin/goldmark@v1.1.30/parser/parser.go:852 +0x7d
github.com/yuin/goldmark/parser.(*parser).walkBlock(0xc00010e000, 0x9747e0, 0xc0001fa700, 0xc00029fd70)
	/home/tdeo/go/pkg/mod/github.com/yuin/goldmark@v1.1.30/parser/parser.go:1103 +0xf8
github.com/yuin/goldmark/parser.(*parser).walkBlock(0xc00010e000, 0x974480, 0xc0001fa680, 0xc00029fd70)
	/home/tdeo/go/pkg/mod/github.com/yuin/goldmark@v1.1.30/parser/parser.go:1101 +0x9d
github.com/yuin/goldmark/parser.(*parser).walkBlock(0xc00010e000, 0x9745a0, 0xc0001fa600, 0xc00029fd70)
	/home/tdeo/go/pkg/mod/github.com/yuin/goldmark@v1.1.30/parser/parser.go:1101 +0x9d
github.com/yuin/goldmark/parser.(*parser).Parse(0xc00010e000, 0x9728e0, 0xc000265420, 0x0, 0x0, 0x0, 0xc00029fe87, 0x9)
	/home/tdeo/go/pkg/mod/github.com/yuin/goldmark@v1.1.30/parser/parser.go:851 +0x2c4
github.com/diamondburned/ningen/md.Parse(0x7f4fc90a2000, 0x6, 0x6, 0x0, 0x0, 0x0, 0x28059fc6, 0x7a10382a9649)
	/home/tdeo/ningen/md/md.go:50 +0x29b
github.com/diamondburned/ningen/md.Fuzz(0x7f4fc90a2000, 0x6, 0x6, 0x4)
	/home/tdeo/ningen/md/fuzz.go:6 +0x68
go-fuzz-dep.Main(0xc00029ff70, 0x1, 0x1)
	go-fuzz-dep/main.go:36 +0x1ad
main.main()
	github.com/diamondburned/ningen/md/go.fuzz.main/main.go:15 +0x52
exit status 2
```

**Comment by diamondburned** [comment]
Tests for these are added in https://github.com/diamondburned/ningen/commit/c57014fa4e4ef6557c99869d28a2d62e9f3cd1fe. Fixed in 1 commit earlier on https://github.com/diamondburned/ningen/commit/e8a0b383f343bf12b7101942154075c917104883.
